<div>
<img src='../pics/banner.PNG'/>
</div>
<div>
<img width="20%" src='../pics/numpy.svg'/>
</div>
<div>
<img width="15%" src='../pics/tinlab.png'/>
<strong>Numpy Arrays - Jeroen Boogaard</strong>
</div>

<h1>Numpy 1: Arrays</h1>
<p>
Een numpy array lijkt op de (builtin) data collection list maar heeft als restrictie dat alle elementen van hetzelfde type moeten zijn. 
</p>

**Imports**

In [2]:
import numpy as np

<p>Numpy <i>cast</i> alle elementen naar hetzelfde type</p>

In [13]:
mixed_list = ["nul", 1]
display(mixed_list)
[ type(item) for item in mixed_list ]

['nul', 1]

[str, int]

In [14]:
mixed_array = np.array(mixed_list)
display(mixed_array)
[ type(item) for item in mixed_array ]

array(['nul', '1'], dtype='<U21')

[numpy.str_, numpy.str_]

**Een <u>vector</u> is een 1-dimensionale lijst van scalars**

In [15]:
n = 10 # Aantal kolommen

## Vector genereren

In [20]:
v1 = np.random.randn(n)
display(v1)
v1.shape

array([ 1.27976974,  0.44532951,  0.07336996,  0.84348765, -2.02638842,
       -0.78480081, -1.25072594, -1.5136656 , -0.29430585, -0.20233632])

(10,)

In [21]:
v2 = np.zeros(n)
display(v2)
v2.shape

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

(10,)

In [22]:
v3 = np.ones(n)
display(v3)
v3.shape

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

(10,)

In [23]:
v4 = np.arange(0, 10)
display(v4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<h3>Exercise 1</h3>
<p>Een vector heeft maar 1 rij. Toon aan dat voor v1 t/m v4 geldt dat het aantal elementen gelijk is aan het aantal kolommen</p>

**Oplossing**

In [24]:
v1.size == v2.size == v3.size == v4.size == n

True

**Rekenen**

In [ ]:
sum(v4, v3)

In [ ]:
v2 - v3