<div>
<img src='../pics/banner.PNG'/>
</div>
<div>
<img width="15%" src='../pics/tinlab.png'/></a>
<strong>Python Basics - Jeroen Boogaard</strong>
</div>

## Numpy - Arrays

**Imports**

In [6]:
import numpy as np

In [7]:
listA = [1, 2, 3, 4]
listA

[1, 2, 3, 4]

In [8]:
arrayA = np.array(listA)
arrayA

array([1, 2, 3, 4])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.arange(1,5,2)

array([1, 3])

In [18]:
np.random.random_sample(5)

array([0.67037705, 0.23725666, 0.00502602, 0.97723087, 0.78569712])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])