<div>
<img src='../pics/banner.PNG'/>
</div>
<div>
<img width="15%" src='../pics/tinlab.png'/>
<strong>Numpy Tensors - Jeroen Boogaard</strong>
</div>

# Numpy Tensors
<p>
Een <strong>Tensor</strong> is een begrip uit de Machine Learning en is Wiskundig gezien een een n-dimensionale matrix.<br>
In Python wordt hiervoor meestal een Numpy Array of een framework-specifieke uitbreiding daarop gebruikt.
</p>

**Imports**

In [41]:
import numpy as np

## Numpy Array
<p>
Een numpy array lijkt op de (builtin) data collection list maar heeft als restrictie dat alle elementen van hetzelfde type moeten zijn. Als dat niet zo is, vindt er automatische casting plaat.
</p>

In [42]:
mixed_list = ["nul", 1]
display(mixed_list)

mixed_array = np.array(mixed_list)
display(mixed_array)

['nul', 1]

array(['nul', '1'], dtype='<U11')

**Conversie tussen Python list en Numpy Array**

In [43]:
listA = [1, 2, 3, 4]
arrayA = np.array(listA)
display( type(arrayA) )
type( arrayA.tolist() ) == type(listA)

numpy.ndarray

True

## Vector
Een 1-dimensionale Numpy Array is een vector van scalars (enkelwaardige numerieke variabelen). 

In [44]:
n = 10

**Vector genereren in Numpy..**

**met willekeurige getallen**
<p>"Ik houd van verrassingen als het maar niet onverwachts is.."</p>

In [45]:
np.random.seed(5)
v1 = np.random.randn(n)
display(v1)
v1.shape

array([ 0.44122749, -0.33087015,  2.43077119, -0.25209213,  0.10960984,
        1.58248112, -0.9092324 , -0.59163666,  0.18760323, -0.32986996])

(10,)

**met nullen of enen**

In [46]:
v2 = np.zeros(n)
display(v2)
v2.shape

v3 = np.ones(n)
display(v3)
v3.shape

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

(10,)

**m.b.v. een reeks**

In [47]:
step = 1
v4 = np.arange(0,n,step)
display(v4)
v4.shape

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

(10,)

**De lengte van een vector is gelijk aan het aantal elementen.**

In [48]:
v1.size == v2.size == v3.size == v4.size == n

True

**Transponeren**
<p>
Transponeren is een bewerking waarbij de kolommen worden omgezet in rijen, <br>
Aangezien een 1-dimensionale Numpy Array maar 1 rij heeft, heeft een transpositie van een vector in Nympy geen effect.
</p>

In [49]:
v1.shape == v1.T.shape
v1

array([ 0.44122749, -0.33087015,  2.43077119, -0.25209213,  0.10960984,
        1.58248112, -0.9092324 , -0.59163666,  0.18760323, -0.32986996])

<p>Om toch een rij-vector om te zetten in een kolomvector kun je gebruikmaken van list comprehension in Python</p>

In [50]:
vTransposed = np.array( [[e] for e in v1] )
vTransposed

array([[ 0.44122749],
       [-0.33087015],
       [ 2.43077119],
       [-0.25209213],
       [ 0.10960984],
       [ 1.58248112],
       [-0.9092324 ],
       [-0.59163666],
       [ 0.18760323],
       [-0.32986996]])

In [51]:
v1.reshape(-1, 1)

array([[ 0.44122749],
       [-0.33087015],
       [ 2.43077119],
       [-0.25209213],
       [ 0.10960984],
       [ 1.58248112],
       [-0.9092324 ],
       [-0.59163666],
       [ 0.18760323],
       [-0.32986996]])

## Matrix
Een 2-dimensionale Numpy Array is een matrix van scalars. 

In [52]:
M0 = np.array(
    [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]
    ]    
)    
display(M0)

middleElement = np.median([i for i in range(M0.size)])
print( f"\nHet middelste element van M0 is {middleElement}" )

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


Het middelste element van M0 is 4.0


In [53]:
shapeM1 = (2, 3)
M1 = np.ones(shapeM1)
display(M1)
print( "M1 is een {0} x {1} matrix".format(shapeM1[0], shapeM1[1]) )

array([[1., 1., 1.],
       [1., 1., 1.]])

M1 is een 2 x 3 matrix


In [54]:
shapeM2 = list( reversed(shapeM1) )
M2 = np.ones(shapeM2)
display(M2)
print( "M2 is een {0} x {1} matrix".format(shapeM2[0], shapeM2[1]) )

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

M2 is een 3 x 2 matrix


**Een <strong>matrix</strong> is een lijst (concatenatie) van vectoren**

In [55]:
listOfVectors = [ 
    v1.tolist(),
    v2.tolist(),
    v3.tolist()
]
matrixFromVectors = np.array(listOfVectors).T
display(matrixFromVectors)
matrixFromVectors.shape

array([[ 0.44122749,  0.        ,  1.        ],
       [-0.33087015,  0.        ,  1.        ],
       [ 2.43077119,  0.        ,  1.        ],
       [-0.25209213,  0.        ,  1.        ],
       [ 0.10960984,  0.        ,  1.        ],
       [ 1.58248112,  0.        ,  1.        ],
       [-0.9092324 ,  0.        ,  1.        ],
       [-0.59163666,  0.        ,  1.        ],
       [ 0.18760323,  0.        ,  1.        ],
       [-0.32986996,  0.        ,  1.        ]])

(10, 3)

### Vermenigvuldigen
Vermenigvulding is alleen mogelijk wanneer het aantal kolommen van de eerste matrix gelijk is aan het aantal rijen van de tweede matrix

In [56]:
(rowsM1, colsM1) = shapeM1
(rowsM2, colsM2) = shapeM2
colsM1 == rowsM2
display(rowsM1)
display(colsM2)

2

2

In [57]:
M3 = M1 @ M2
display(M3)
(rowsM3, colsM3) = M3.shape
print( "M3 is een {0} x {1} matrix".format(rowsM3, colsM3) )

array([[3., 3.],
       [3., 3.]])

M3 is een 2 x 2 matrix


**Omdat vectoren maar 1 dimensie hebben (1 rij OF 1 kolom), is het <i>vectorproduct</i> op 2 manieren gedefinieerd..**

In [58]:
# 1 x 2
v = np.array( [0, 1] )
# 2 x 1
w = np.array( [[2], [3]] ) 

**Inwendig product**<br>
Dit resulteert in een scalar:<br>
(1 x n) * (n * 1)

In [59]:
# 1 x 1
pIn = v @ w
display(pIn.tolist())
pIn.shape

[3]

(1,)

**Uitwendig product**

In [ ]:
# 2 x 2
pUit = np.multiply(v, w)
pUit.shape
display(pUit)