<div>
<img src='../pics/banner.PNG'/>
</div>
<div>
<img width="15%" src='../pics/tinlab.png'/>
<strong>Pytorch Tensors - Jeroen Boogaard</strong>
</div>

# Pytorch Tensors
<p>
Een <strong>Tensor</strong> is een begrip uit de Machine Learning en is Wiskundig gezien een een n-dimensionale matrix.<br>
In Python wordt hiervoor meestal een Numpy Array of een framework-specifieke uitbreiding daarop gebruikt.
</p>

**Imports**

In [70]:
import numpy as np
import torch

## Pytorch Tensor
<p>
Een Pytorch tensor is een variant van een Numpy Array.
</p>

**Conversie tussen Python list, Numpy Array en Pytorch Tensor**

In [71]:
listA = [1, 2, 3, 4]
arrayA = np.array(listA)
display(arrayA)
tensorA = torch.from_numpy(arrayA)
display(tensorA)
tensorA.tolist()
torch.tensor(listA)

array([1, 2, 3, 4])

tensor([1, 2, 3, 4], dtype=torch.int32)

tensor([1, 2, 3, 4])

## Vector
Een 1-dimensionale Tensor is een vector van scalars (enkelwaardige numerieke variabelen). 

In [72]:
n = 10

**Vector genereren in Pytorch..**

**met willekeurige getallen**

In [73]:
v1 = torch.randn(n)
display(v1)
v1.shape

tensor([ 0.5701,  0.3885,  1.6564, -1.7817, -1.5320, -0.6121, -0.8294,  0.4345,
         1.8247, -0.8126])

torch.Size([10])

**met nullen of enen**

In [74]:
v2 = torch.zeros(n)
display(v2)
v2.shape

v3 = torch.ones(n)
display(v3)
v3.shape

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

torch.Size([10])

**m.b.v. een reeks**

In [75]:
step = 1
v4 = torch.arange(0,n,step)
display(v4)
v4.shape

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

torch.Size([10])

**De lengte van een vector is gelijk aan het aantal elementen.**

In [76]:
v1.size == v2.size == v3.size == v4.size == n

False

**Transponeren**
<p>
Transponeren is een bewerking waarbij de kolommen worden omgezet in rijen, <br>
Aangezien een 1-dimensionale Numpy Array maar 1 rij heeft, heeft een transpositie van een vector in Nympy geen effect.
</p>

In [77]:
v1.shape == v1.T.shape

True

<p>Om toch een rij-vector om te zetten in een kolomvector kun je gebruikmaken van list comprehension in Python</p>

In [78]:
v1 = torch.randn(n)
display(v1.shape)
vTransposed = torch.from_numpy( np.array([[e] for e in v1]) )
vTransposed.shape

torch.Size([10])

torch.Size([10, 1])

## Matrix
Een 2-dimensionaleTensor is een matrix van scalars. 

In [79]:
# M0 = np.array(
M0 = torch.tensor(
    [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]
    ]    
)    

display(M0)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## References

[pytorchTutorial](https://github.com/patrickloeber/pytorchTutorial)<br>
[Convert pandas DataFrame to PyTorch Tensor](https://blog.finxter.com/5-best-ways-to-convert-pandas-dataframe-to-pytorch-tensor/)